### ISSUE TITLE
Bioarchaeology and archaeogenetics

### ISSUE THREAD

**Issue by nevrome** [zackbatist/open-archaeo#20]
James PR (#19) is kind of related to the question how open-archaeo should cover the rather big world of aDNA-related bioinformatics. Having `archaeodiet` and `gargammel` in the list is kind of arbitrary, given that there is a lot more aDNA software.

Where did you want to draw the line here, @zackbatist? Intuitively I would have suggested to leave it out, except for tools that are very clearly intended for use by archaeologists. The overwhelming majority of aDNA software is written by geneticists for geneticists. On the other hand James also pointed out to me that there is no comprehensive aDNA software list so far (at least to our knowledge).

**Comment by joeroe** [comment]
Not to speak for @zackbatist, but I added that tag and most of these entries and afterwards we did talk a bit about where to draw the line. As you say, including all aDNA tools would be too much, but the ones more directly related to archaeology could be included. The current list probably needs some pruning to actually stick to that logic.

**Comment by MartinHinz** [comment]
@joeroe , agreed. Since the selection will always be subjective, and both fields are intertwined anyway, I would include everything that the owner of the repo has the feeling that it is really immediatly helpful for archaeologists rather than for paleogeneticists?

**Comment by zackbatist** [comment]
This list is always going to have an arbitrary scope, the best we can do is be clear in our decisions. Personally, I prefer to keep a broad scope. And as @MartinHinz pointed out it's also a matter of the maintainers of each project identifying the item as related to archaeology. Maintainers identifying their repos as relating to archaeology not only serves to delimit what should or should not be included, but also frames the potential for items to be discovered and included in open-archaeo at all.

To illustrate this point, the main discovery mechanism I've used is identifying a repo I don't recognize (typically by happenstance) and checking out the profiles and all other repos created by its contributors, and repeat this until I've gone through the entire cluster -- basically a manual crawl. If I don't see any key words that identify it as relating to archaeology (archaeo*, palaeo*, etc) at all during a cursory scan, then I tend to move on. Another way new entries are added is through maintainers getting in touch directly or submitting a PR to include their software.

All that being said, perhaps we should identify a few areas like archaeogenetics, palaeoenvironment reconstruction, XRF/elemental analysis, aerial scanning, tablet recording interfaces, etc that might benefit from a deep dive, in order to ensure that we have included all existing relevant tools, and perhaps also designate categories for those that are tangential to our main scope.

I generally need to do a better job curating tags and categories and delimiting their scopes. @joeroe and I have discussed documenting each tag more thoroughly to help make this a more useful dataset, but my progress has been halted by other work that has cropped up.

**Comment by jfy133** [comment]
Just to jump in (as I had said privately to @nevrome ) - if you do decide to go the 'broad' route - I am happy to help with a 'brain dump' of aDNA tools.

My background is actually in archaeology (B.Sc.), so I also have a rough feeling of what is specifically archaeo/palaeogenetics vs. just genetics (or aDNA of ecology etc).

Let me know if you're interested.

**Comment by nevrome** [comment]
I could very well imagine to join @jfy133 in providing a software list at the interface of archaeology and archaeogenetics. I hope our poseidon project will soon be ready to fit exactly into this gap :wink: 

Beyond that it might be a fun task for the SIG to cover these specific domains you listed, Zack. We could split up into small teams to do some of these deep dives.

**Comment by zackbatist** [comment]
That would be really helpful! It would also be really helpful if you could identify what is meant by the term archaeo/palaeogenetics, as wel as other related terms. I must admit that I have very little experience with that/those fields, so getting some input with people who are actually more familiar with it would be fantastic.

**Comment by jfy133** [comment]
Ooof, good question ;).

I would define archaeogenetics being the analysis of degraded DNA from archaeological/anthropological sources (skeletons of humans/domesticate animal/plants, artefacts, hominin DNA from cave sediments etc.). Palaeogenetics could be considered more broad and could include less _archaeology_ related stuff such as degraded DNA from sediment to address ecological questions etc.

Generally most archaeogenetic tools will be related specifically for accounting for the degraded DNA part.

**Comment by jfy133** [comment]
A little brain dump of software while it was relevent for some thing else (and later why it's specific to aDNA)

# Pipelines

- paleomix
- epiPALEOMIX
- eager
- nf-core/eager
- [ATLAS](https://bitbucket.org/wegmannlab/atlas/wiki/Home)
- coproID(?)

# Damage profilers

- mapDamage2
- DamageProfiler

# Metagenomic classifers

- metaBit
- MALT
- SPARSE(?)
- HOPS

# aDNA Simulators

- gargammel
- adrsm
- TAPAS
- 
# aDNA Damage-aware Genotypers

- snpAD
- ANTcaller
- ARIADNA

# Low-coverage contamination estimation

- contaMix (?)
- AuthentiCT
- Schmutzi

# Low-coverage adapted population-genetics tools

- sexDetERRmine(?)
- MultiVCFAnalyzer(?)
- PMDtools
- lcMLkin
- READ

**Comment by nevrome** [comment]
Can't add much to that!

- Stephan's [pileupCaller](https://github.com/stschiff/sequenceTools#pileupcaller) for *aDNA Damage-aware Genotypers*
- [ANGSD](http://www.popgen.dk/angsd/index.php/ANGSD) and ContamMix (afaik no homepage) for *Low-coverage contamination estimation*
- [hapROH](https://github.com/hringbauer/hapROH) for *Low-coverage adapted population-genetics tools*

**Comment by jfy133** [comment]
Yeah I couldn't find contamMix either, seems to be some random script floating around colleague networks.

I originally had put angsd in the list, but when I was putting it into nf-core/eager, I noticed it seemed to actually be a mostly pop-gen tool, with only a couple of functions adapted for low coverage thrown in. So I'm not sure if that should be included or not. On the otherhand those functions are very commonly used...

**Comment by jfy133** [comment]
Note to self, a few more:

Leehom
DATES 
Dice 
Anfo
Consensify
Mia

**Comment by TCLamnidis** [comment]
Nothing to add currently, but just confirming:
To my knowledge, ContamMix is available by request from the author and has no homepage indeed.

**Comment by jfy133** [comment]
I've added links to my weekend brain dump.

I would remove contamMix for that reason. It's not open per-se.

**Comment by jfy133** [comment]
A few more:

- [pathPhynder](https://github.com/ruidlpm/pathPhynder/)
- [CASCADE](https://www.frontiersin.org/articles/10.3389/fevo.2020.00185/full) (this is actually a LIMS rather than analytical software, but it is specifically for aDNA)
- [DamMet](https://github.com/KHanghoj/DamMet)
- [MADAM](https://github.com/Integrative-Transcriptomics/MADAM)

**Comment by jfy133** [comment]
@zackbatist would you be against me tweeting for suggestions? Can ask the community if we're missing anything...

**Comment by jfy133** [comment]
To make things easier for @zackbatist : https://github.com/zackbatist/open-archaeo/pull/22

Adds all the above, and corrects some things. Please check everything. In particular I wasn't sure how multiple authors work or should be displayed. E.g. for `nf-core` pipelines is from the organisation, but I know who the authors are, however in some cases this coule be a lot..

**Comment by zackbatist** [comment]
Thanks @jfy133 ! I updated #22, see my comment there for further action required. Feel free to share this, we can use as much domain expertise as we can get!

Authorship is still a bit of a mess, partly due to restrictions imposed by the spreadsheet format, and partly due to the different affordances for collaboration in open source software development than what researchers may be used to. Currently I'm just going with the repository's maintainer plus any contributors who are explicitly referred to in the readme or in other documentation that is easy to come across. Please add any individual authors, as you see fit.

**Comment by altinisik** [comment]
Great list! Thanks for the effort. 

[ContamLD](https://github.com/nathan-nakatsuka/ContamLD) for _Low-coverage contamination estimation_

**Comment by jfy133** [comment]
Self Note: the thing from Becky Cribdon/Allaby lab that I'm blanking on the name at the moment

**Comment by jfy133** [comment]
@zackbatist @nevrome  I think we're done for now, so this issue could be closed. However, I notice that the website itself hasn't updated. 

Note that in my PRs I only updated the CSV and no other files, so depending where the website draws from maybe a new PR needs to be made (unless you only update the website periodicially)

**Comment by zackbatist** [comment]
Just updated the site manually, thanks for the reminder.

**Comment by bbartholdy** [comment]
James, is there a reason you left out [cuperdec](https://github.com/jfy133/cuperdec)?

**Comment by jfy133** [comment]
> @jfy133, is there a reason you left out [cuperdec](https://github.com/jfy133/cuperdec)?

'Cauuussseeee I forgot 😬

https://github.com/jfy133/cuperdec

**Comment by bbartholdy** [comment]
> > @jfy133, is there a reason you left out [cuperdec](https://github.com/jfy133/cuperdec)?
> 
> 'Cauuussseeee I forgot grimacing
> 
> https://github.com/jfy133/cuperdec
> 
> https://cran.r-project.org/web/packages/cuperdec/index.html

I didn't realise it's on cran now, congrats!

**Comment by zackbatist** [comment]
Thanks, just merged this PR in.
